import { useUser } from "@auth0/nextjs-auth0/client";
import Head from "next/head";
import Link from "next/link";
useUser;
export default function Home() {
	const { user, error, isLoading } = useUser();
	if (isLoading) return <div>...loading</div>;
	if (error) return <div>{error.message}</div>;
	if (user) {
		return (
			<>
				Welcome, {user.name}
				<br />
				<Link href={"/api/auth/logout"}>Logout</Link>
			</>
		);
	}
	return <Link href={"/api/auth/login"}>Login</Link>;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Main page</h1>
		</>
	);
}
